namespace: thulium_drake
name: general
version: VERSION
readme: README.md
authors:
  - Jeffrey van Pelt <jeff@vanpelt.one>

description: Collection of all roles I publish on Galaxy/Github and some other tools I use
license:
  - GPL-2.0-or-later
repository: https://github.com/Thulium-Drake/ansible-collection-general
