---
name: Publish
run-name: Publish collection on Ansible Galaxy
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '@weekly'
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'

jobs:
  publish:
    runs-on: rhel-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Publish to Galaxy
        run: |
          cd ${{ forgejo.workspace }}
          echo "token: $GALAXY_TOKEN" > ~/.galaxy_token
          ./build_collection.sh
        env:
          ANSIBLE_GALAXY_TOKEN_PATH: '~/.galaxy_token'
          GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_BASE_URL: ${{ vars.GIT_BASE_URL }}
          GIT_USER: ${{ vars.GIT_USER }}
          GIT_ORG_UID: ${{ vars.GIT_ORG_UID }}
