---
name: Publish
run-name: Publish collection on Ansible Galaxy
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '@weekly'
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Ensure Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ansible
        run: |
          python -m pip install ansible-core
      - name: Publish to Galaxy
        run: |
          cd ${{ gitea.workspace }}
          echo "token: $GALAXY_TOKEN" > ~/.galaxy_token
          ./build_collection.sh
        env:
          ANSIBLE_GALAXY_TOKEN_PATH: '~/.galaxy_token'
          GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_BASE_URL: ${{ vars.GIT_BASE_URL }}
          GIT_USER: ${{ vars.GIT_USER }}
          GIT_ORG_UID: ${{ vars.GIT_ORG_UID }}
